const chapters = [
  {
    id: "ch1",
    number: "01",
    title: "Overview of Software Security",
    source: "Chapter 1, 59 slides",
    summary:
      "Software security means engineering software so it still works correctly under malicious attack. This chapter sets the vocabulary, the three pillars, the RMF loop, touchpoints, secure SDLC thinking, quality versus security, and threat modeling.",
    sections: [
      {
        heading: "What software security means",
        source: "Ch.1 p.4-p.8",
        bullets: [
          "Software security is the idea of building software so it continues to function correctly even when someone attacks it.",
          "Security should be addressed from the early stages of the SDLC, not only after coding is finished.",
          "The slide summary states that security is risk management.",
          "Many systems are insecure because of lack of secure-method education, weak design thinking, lack of testing, and poor development environments.",
          "CIA goals: Confidentiality protects information from unauthorized disclosure; Integrity prevents unauthorized alteration; Availability keeps information or services ready when required."
        ]
      },
      {
        heading: "Important terms",
        source: "Ch.1 p.7-p.8",
        bullets: [
          "Defect: a problem that deviates from requirements or specifications. Example from the slide: requirement says password length must be at least 8, but the app allows 5.",
          "Bug: an implementation-level or coding error that makes software behave incorrectly. Example: app crashes when Login is clicked.",
          "Flaw: a weakness in design, architecture, or logic. Example: storing passwords in plain text.",
          "Failure: the software cannot perform its required function.",
          "Risk: the probability that a flaw or bug will affect the software purpose, multiplied by impact.",
          "Vulnerability: a weakness or error an attacker can exploit. It can come from design or implementation. Design-level vulnerabilities are the hardest to handle."
        ]
      },
      {
        heading: "Three pillars of software security",
        source: "Ch.1 p.9-p.10, p.20, p.40-p.41",
        bullets: [
          "Pillar 1 - Risk Management: identifies, ranks, tracks, and understands software security risks.",
          "Pillar 2 - Touchpoints: security activities placed through the lifecycle, such as abuse cases, requirements, architecture risk analysis, testing, code review, penetration testing, and operations.",
          "Pillar 3 - Knowledge: gathering and sharing security knowledge such as principles, guidelines, rules, vulnerabilities, exploits, attack patterns, and historical risks."
        ]
      },
      {
        heading: "Risk Management Framework (RMF)",
        source: "Ch.1 p.10-p.18",
        bullets: [
          "RMF gives a consistent and continuous approach to tracking and handling risks.",
          "Step 1 - Understand business context: extract business goals, identify critical assets and operations, understand which risks matter, gather artifacts, and research the project scope.",
          "Step 2 - Identify business and technical risks: identify threats and vulnerabilities, analyze likelihood, map technical risks to business goals, create risk questionnaires, interview the team, and analyze the data.",
          "Step 3 - Synthesize, prioritize, and rank risks: rank based on business goals, likelihood, impact, and number of risks over time. Ask what to do first and how to allocate resources.",
          "Step 4 - Define mitigation strategy: consider cost, implementation time, chance of success, competence, and impact. Identify validation techniques and use cost-benefit thinking.",
          "Step 5 - Carry out fixes and validate: implement mitigations, rectify artifacts, measure progress against the strategy, and validate that unacceptable risk is gone.",
          "RMF is a multilevel loop with measurement and reporting. Risk identification once is incorrect; assessment must repeat throughout the project."
        ]
      },
      {
        heading: "Touchpoint 1: abuse cases",
        source: "Ch.1 p.21-p.22",
        bullets: [
          "Abuse cases describe what the software cannot and will not do, including abnormal behavior.",
          "Do not assume no one would try strange actions. Attackers often test those assumptions.",
          "Anti-requirements help reveal how attackers approach system assumptions. They should be used throughout the lifecycle and generated by security analysts.",
          "Attack models consider well-known attacks, select patterns relevant to the system, build abuse cases around them, and include anyone who can access the system."
        ]
      },
      {
        heading: "Touchpoint 2: security requirements",
        source: "Ch.1 p.23-p.24",
        bullets: [
          "Security requirements cover functional security and emergent characteristics.",
          "They must satisfy three criteria: Definition, Assumption, and Satisfaction.",
          "Definition means the security requirement is explicitly stated.",
          "Assumption means the system behavior assumptions are considered.",
          "Satisfaction means the security goals are met by requirements, and the system meets those requirements.",
          "Slide example: user access management should ensure authorized access and prevent unauthorized access. Formal user registration and de-registration should enable assignment of access rights.",
          "Slide example: all users should have a unique user ID and password for personal use, so actions can be traced. User IDs of people who left the organization must be disabled or removed."
        ]
      },
      {
        heading: "Touchpoint 3: architectural risk analysis",
        source: "Ch.1 p.25-p.30",
        bullets: [
          "Architecture risk analysis detects design flaws. The slides state design flaws account for 50 percent of security problems and cannot be found just by staring at code.",
          "It tracks risk over time, links system-level concerns to probability and impact, and fits with RMF.",
          "Critical aspects: Attack Resistance Analysis, Ambiguity Analysis, and Weakness Analysis.",
          "Attack Resistance Analysis uses secure design checklists, maps attack patterns from abuse cases or historical risks, identifies architectural risks, and demonstrates known attacks.",
          "Ambiguity Analysis is creative work to find new risks. It needs at least two analysts and experience.",
          "Weakness Analysis studies the impact of software dependencies and asks what happens when assumptions about external software fail.",
          "Diagram examples include data stores, OS processes, data flows, HTTPS, external interactors, and a trust boundary.",
          "Risk register examples include stolen API keys, client-side price manipulation, admin console without MFA, misconfigured object storage, DDoS against checkout, and insufficient logging."
        ]
      },
      {
        heading: "Touchpoint 4: risk-based security testing",
        source: "Ch.1 p.31-p.33",
        bullets: [
          "Risk-based testing is grounded in system architecture and attacker mindset.",
          "It focuses on areas where an attack is likely to succeed.",
          "It differs from penetration testing because it is inside-out and begins before the software is complete, even before system integration.",
          "Two approaches: functional security testing from security requirements, and adversarial testing from abuse cases and architecture risk analysis.",
          "Slide test examples: unauthorized admin action should return 403 Forbidden; long input should be rejected or truncated without crashing; price tampering should be recalculated or validated by the server; executable upload disguised as JPG should be rejected or served safely; rapid login attempts should trigger rate limiting or lockout."
        ]
      },
      {
        heading: "Touchpoints 5-7: code review, penetration testing, operations",
        source: "Ch.1 p.34-p.39",
        bullets: [
          "Code review is source code analysis focused on finding and fixing bugs. Static analysis tools can find security bugs but can produce false positives and false negatives.",
          "Example tools named in the slides: Coverity, Fortify, Ounce Labs, and Secure Software.",
          "Useful source code tools should be designed for security, support multiple tiers, be extensible, help analysts and developers, fit existing processes, and make sense to multiple stakeholders.",
          "Slide code review example: converting input directly with int(age) can crash on invalid input; validating age.isdigit() first is safer.",
          "Software penetration testing evaluates security by simulating an outside-in attack against the final system. The slides call it the most applied of the seven touchpoints.",
          "Penetration testing may use static and dynamic tools. Examples named: fault injection tools, Cenzic, Holodeck, SPI Dynamics, Immunity CANVAS, and IEInspector HTTP Analyzer.",
          "Security operations can connect software security operations with network security operations. Lessons from attacks should feed back into development."
        ]
      },
      {
        heading: "SDLC and quality versus security",
        source: "Ch.1 p.42-p.47",
        bullets: [
          "SDLC phases: Planning, Design, Implementation, Testing, Deployment, Maintenance.",
          "Quality code focuses on functionality, performance, usability, and maintainability. Its goal is meeting user requirements and performing tasks efficiently.",
          "Secure code focuses on protection against threats, vulnerabilities, and attacks. Its goal is confidentiality, integrity, and availability.",
          "Quality examples: fewer bugs and crashes, well documented, easy to maintain, fast and reliable.",
          "Security examples: proper input validation, safe authentication and access control, resilience against SQL injection and buffer overflows.",
          "Comparison table: quality objective is correct and efficient work; secure objective is protection from malicious use. Quality testing is functional testing and QA; secure testing is security testing and penetration tests.",
          "High quality does not equal secure. Secure does not equal high quality. Best practice is balancing both: Quality + Security = Reliable Software."
        ]
      },
      {
        heading: "Threat modeling process",
        source: "Ch.1 p.48-p.58",
        bullets: [
          "Threat modeling is a structured security technique for identifying security objectives, threats, and vulnerabilities.",
          "It supports design and engineering decisions and helps decide where to prioritize secure design, development, and deployment work.",
          "The process is iterative and each step uses inputs and produces outputs.",
          "Step 1 - Identify security objectives using CI4AM: Confidentiality, Integrity, Availability, Authentication, Authorization, Auditing, and Management. Sources include policies, standards, legal or compliance directives, and business requirements.",
          "Example objectives: prevent data theft, protect IP, attain compliance, and provide high availability.",
          "Step 2 - Application overview: deployment location, users or actors, data elements, actor rights, technologies, security mechanisms, use cases, functional specifications, and architecture diagrams.",
          "Step 3 - Decompose the application: identify exit points, data flows, trust boundaries, and entry points such as ports, pages, components, APIs, and stored procedures.",
          "Step 4 - Identify threats that apply to the actual context. Approaches include attack trees and thinking like an attacker. Threat examples include SQL injection, XSS, replay attacks, MITM, and eavesdropping.",
          "STRIDE: Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege.",
          "DREAD: Damage Potential, Reproducibility, Exploitability, Affected Users, Discoverability.",
          "Step 5 - Identify vulnerabilities linked to the threats. Examples: weak encryption, clear text credentials, unhandled exception, dynamic SQL, and long session timeouts.",
          "Ranking gives insight into risk. Risks can be accepted, mitigated, transferred, or ignored. The slides warn to avoid ignoring risk.",
          "Probability x Impact ranking uses High = 15, Medium = 10, Low = 5.",
          "DREAD average formula: (Damage + Reproducibility + Exploitability + Affected Users + Discoverability) / 5."
        ]
      }
    ],
    memory: [
      "CIA: Confidentiality, Integrity, Availability.",
      "RTK pillars: Risk Management, Touchpoints, Knowledge.",
      "UISDF risk loop: Understand context, Identify risks, Synthesize and rank, Define mitigation, Fix and validate.",
      "DAS security requirements: Definition, Assumption, Satisfaction.",
      "STRIDE: Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege.",
      "DREAD: Damage, Reproducibility, Exploitability, Affected Users, Discoverability."
    ],
    flashcards: [
      ["What is software security?", "Engineering software so it keeps functioning correctly under malicious attack."],
      ["What are the three pillars of software security?", "Risk Management, Touchpoints, and Knowledge."],
      ["Why is risk assessment not a one-time task?", "RMF is a continuous loop; risks must be identified and assessed repeatedly throughout the project."],
      ["What is the main difference between quality code and secure code?", "Quality code works correctly and efficiently; secure code protects against threats and attacks."],
      ["What does STRIDE help identify?", "Threat categories: spoofing, tampering, repudiation, information disclosure, denial of service, and elevation of privilege."]
    ],
    quiz: [
      {
        question: "Which statement best matches the slide definition of software security?",
        options: ["Fast software with few bugs", "Software that continues to function correctly under malicious attack", "Software with a modern user interface", "Software that has no maintenance cost"],
        answer: 1,
        explain: "Chapter 1 defines software security as engineering software so it continues to function correctly under malicious attack."
      },
      {
        question: "Which RMF step comes after identifying business and technical risks?",
        options: ["Carry out fixes", "Synthesize, prioritize, and rank risks", "Deploy software", "Write user documentation"],
        answer: 1,
        explain: "The RMF sequence is Understand, Identify, Synthesize, Define mitigation, then Fix and validate."
      },
      {
        question: "In DREAD, what does A stand for?",
        options: ["Authentication", "Affected Users", "Attack Tree", "Availability"],
        answer: 1,
        explain: "DREAD means Damage, Reproducibility, Exploitability, Affected Users, Discoverability."
      }
    ]
  },
  {
    id: "ch2",
    number: "02",
    title: "Secure Software Development Lifecycle (SSDLC)",
    source: "Chapter 2, 36 slides",
    summary:
      "This chapter explains security maturity, how security maps into every SDLC phase, ISO/IEC 27034, OWASP Top 10, CWE, and software development methodologies.",
    sections: [
      {
        heading: "OWASP SAMM",
        source: "Ch.2 p.3-p.7",
        bullets: [
          "OWASP SAMM means Software Assurance Maturity Model. The slides describe OWASP as Open Worldwide Application Security Project.",
          "SAMM is an open-source framework for software security maturity.",
          "It helps organizations evaluate current practices, build an improvement roadmap, and measure progress over time.",
          "Five business functions: Governance, Design, Implementation, Verification, and Operations.",
          "Each function has two practices: Governance has Strategy & Metrics and Policy & Compliance; Design has Threat Assessment and Security Requirements; Implementation has Secure Build and Secure Deployment; Verification has Security Testing and Security Review; Operations has Incident Management and Environment Management.",
          "Maturity levels: Level 1 is ad-hoc or basic; Level 2 is defined, repeatable, and organization-wide; Level 3 is optimized, measured, and continuously improved.",
          "Example workflow: assess with SAMM, set target maturity, then make an improvement plan such as governance committee, threat modeling workshops, OWASP Top 10 training, SAST/DAST tools, penetration tests, CI/CD checks, incident response playbooks, and monitoring dashboards."
        ]
      },
      {
        heading: "Application security risk",
        source: "Ch.2 p.8-p.10",
        bullets: [
          "Attackers may use many paths through an application to harm the business or organization.",
          "Each path is a risk; some are easy to find and exploit, while others are difficult.",
          "Overall risk is determined by likelihood factors such as threat agent, attack vector, and security weakness, combined with technical and business impact.",
          "Technical impact examples: decreased privacy, stolen sensitive data, disabled computers.",
          "Business impact examples: delayed sales or income and increased expenses."
        ]
      },
      {
        heading: "Security in each SDLC phase",
        source: "Ch.2 p.11-p.16",
        bullets: [
          "Planning and Requirements: perform risk assessment, create abuse cases, and define security plus functional requirements early.",
          "Design: use threat modeling and secure design principles such as least privilege and defense in depth.",
          "Implementation: train developers in secure coding to prevent common vulnerabilities such as SQL injection and XSS; perform security-focused code reviews.",
          "Testing: use static analysis, dynamic analysis, penetration testing, vulnerability scanning, risk-based security testing, and automated tools.",
          "Deployment: apply secure configuration management and strict access controls such as roles.",
          "Maintenance: keep software and dependencies updated and maintain an incident response plan."
        ]
      },
      {
        heading: "ISO/IEC 27034 application security",
        source: "Ch.2 p.17-p.20",
        bullets: [
          "ISO/IEC 27034 belongs to the ISO 27000 family and focuses on application security during the software lifecycle.",
          "It provides guidelines, principles, and frameworks for secure applications.",
          "Why it matters: applications are major attack targets; common risks include SQL injection, XSS, and broken authentication; secure applications protect data, business, and users; it supports compliance.",
          "27034-1 introduces concepts such as ASC, ASCL, ASLC, ASMP, and ONF.",
          "27034-2 covers the Organization Normative Framework, meaning policies, standards, and procedures for application security.",
          "27034-3 covers Application Security Management Process, practical guidance for managing application security.",
          "27034-4 covers Application Security Validation, how to validate that an application meets security requirements.",
          "27034-5 covers protocol bindings; 27034-6 covers case studies; 27034-7 covers Assurance Prediction Framework.",
          "ASC is a specific security function, such as input validation, HTTPS, or encrypting credit card numbers.",
          "ASCL is a reusable catalog of ASCs, such as payment encryption controls or session timeout controls.",
          "ASLC is secure design, development, testing, deployment, and maintenance across the lifecycle.",
          "ASMP is the governance process that ensures continuous app security.",
          "ONF is reusable policies, standards, guidelines, and resources that guide secure application development and maintenance.",
          "The slides state ISO/IEC 27034 provides the framework but not a ready-made list of controls. Other standards provide controls: ISO/IEC 27001, OWASP ASVS, PCI DSS, NIST SP 800-53, and CWE.",
          "The slide names ANF as an ISO/IEC 27034 concept but does not define it."
        ]
      },
      {
        heading: "OWASP Top 10 risks",
        source: "Ch.2 p.21-p.25",
        bullets: [
          "OWASP Top 10 lists the ten most critical web application security risks and helps organizations prioritize security effort.",
          "1 Broken Access Control: users do things they should not, such as normal users accessing admin functions or other users' data.",
          "2 Cryptography Failures: weak, missing, or misused encryption exposes sensitive data. Decide protection needs for data in transit and at rest.",
          "3 Injection: malicious data such as SQL, commands, or XSS tricks the program into running unintended commands. Source code review is best for detecting vulnerable applications, and automated testing of parameters, headers, URLs, cookies, JSON, SOAP, and XML is encouraged.",
          "4 Insecure Design: architectural or design flaws create weaknesses. Threat modeling should be integrated into refinement sessions or similar activities.",
          "5 Security Misconfiguration: poor settings such as default passwords, open cloud storage, or unnecessary features.",
          "6 Vulnerable and Outdated Components: old libraries, frameworks, or software with known bugs.",
          "7 Identification and Authentication Failures: weak login systems, password reset problems, missing MFA, or session problems.",
          "8 Software and Data Integrity Failures: software or data is not properly verified, such as untrusted updates or supply chain attacks.",
          "9 Security Logging and Monitoring Failures: missing, weak, or ignored logs prevent detection, escalation, and response.",
          "10 Server-Side Request Forgery: the server is tricked into making requests to unexpected destinations because user-supplied URLs are not validated."
        ]
      },
      {
        heading: "CWE and its relationship to OWASP",
        source: "Ch.2 p.26-p.30",
        bullets: [
          "CWE means Common Weakness Enumeration. It is a catalog of common software coding mistakes or weaknesses.",
          "The slides state CWE is published and maintained by MITRE, and each weakness has a unique ID such as CWE-20.",
          "CWE helps developers know coding errors to avoid, helps testers check for known flaws, and helps organizations set coding standards and measure maturity.",
          "Slide CWE examples: CWE-20 Improper Input Validation, CWE-74 Injection, CWE-120 Buffer Overflow, CWE-119 Memory Bound Error, CWE-384 Session Fixation, CWE-287 Improper Authentication, CWE-316 Cleartext Storage in Memory, CWE-117 Improper Logging, CWE-223 Missing Security Info, CWE-209 Info Exposure in Error Message, CWE-200 Information Exposure.",
          "OWASP Top 10 is risk-focused from the attacker's view. CWE is weakness-focused from the developer's view.",
          "OWASP is high-level, such as Broken Access Control. CWE is lower-level and detailed, such as CWE-284 Improper Access Control or CWE-285 Improper Authorization.",
          "Each OWASP category can map to many CWE entries, and each CWE entry can belong to one or more OWASP risk categories."
        ]
      },
      {
        heading: "Development methodologies",
        source: "Ch.2 p.31-p.35",
        bullets: [
          "Waterfall is linear. The slides say security is often added late, reactive, and flaws are found during testing.",
          "V-Model maps testing to every stage and can map security testing, but has limited flexibility.",
          "Spiral is risk-driven and iterative, with security considered early through threat and risk analysis.",
          "RUP is iterative and architecture-centric, with security in requirements and design.",
          "Agile is fast and adaptable, but security is often ignored.",
          "Secure Agile or DevSecOps adds security in every sprint, threat modeling, and automated CI/CD testing.",
          "Microsoft SDL includes security in all phases, including threat modeling, secure coding, testing, and incident response.",
          "OWASP SAMM assesses and improves security practices."
        ]
      }
    ],
    memory: [
      "SAMM functions: G-D-I-V-O = Governance, Design, Implementation, Verification, Operations.",
      "SAMM levels: 1 basic, 2 defined, 3 optimized.",
      "SDLC security map: Plan risks, Design threats, Implement safely, Test deeply, Deploy securely, Maintain updates.",
      "OWASP vs CWE: OWASP is risk view; CWE is weakness view."
    ],
    flashcards: [
      ["What does SAMM help an organization do?", "Assess current security practices, create a roadmap, and measure improvement over time."],
      ["Name the five SAMM business functions.", "Governance, Design, Implementation, Verification, Operations."],
      ["What is CWE?", "A catalog of common software weaknesses, each with a unique ID."],
      ["How does ISO/IEC 27034 differ from control catalogs?", "It gives the application security framework and process, while other standards provide ready control lists."],
      ["What is the key difference between OWASP Top 10 and CWE?", "OWASP groups high-level application risks; CWE catalogs lower-level coding and design weaknesses."]
    ],
    quiz: [
      {
        question: "Which SAMM function includes Security Testing and Security Review?",
        options: ["Governance", "Implementation", "Verification", "Operations"],
        answer: 2,
        explain: "Verification contains Security Testing and Security Review."
      },
      {
        question: "Which SDLC phase includes secure configuration and strict access controls before release?",
        options: ["Planning", "Deployment", "Implementation", "Maintenance"],
        answer: 1,
        explain: "Deployment covers secure configuration management and access controls."
      },
      {
        question: "Which item is a CWE example from the slides?",
        options: ["CWE-20 Improper Input Validation", "CWE-10 Broken Access Control", "CWE-27034 ONF", "CWE-SAMM Governance"],
        answer: 0,
        explain: "CWE-20 Improper Input Validation is listed in Chapter 2."
      }
    ]
  },
  {
    id: "ch3",
    number: "03",
    title: "Handling Input",
    source: "Chapter 3, 30 slides",
    summary:
      "This chapter explains trusted and untrusted input, validation, syntactic and semantic checks, safe processing, SQL injection examples, and prevention of sensitive data exposure.",
    sections: [
      {
        heading: "Why input handling matters",
        source: "Ch.3 p.3-p.5",
        bullets: [
          "Handling input is critical to software security because input can come from users, other systems, or external sources.",
          "Input may contain malicious code or data that compromises the software.",
          "Before processing input, classify it by source, format, and content.",
          "Trusted input comes from reliable sources such as internal systems or trusted users.",
          "Untrusted input comes from unknown or external sources, such as web users or external systems.",
          "Reasons to validate: prevent SQL injection, XSS, command injection, and malicious scripts; protect database integrity; ensure data accuracy; prevent system crashes; maintain system reliability."
        ]
      },
      {
        heading: "Input validation basics",
        source: "Ch.3 p.6",
        bullets: [
          "Input validation checks whether input is valid and meets specific requirements or constraints.",
          "Objectives include allowing only alphanumeric characters where needed, checking acceptable value ranges, and preventing malicious code or characters.",
          "Input filtering means accepting only the good stuff.",
          "Input sanitization means cleaning what is dirty.",
          "Input normalization means making input consistent before processing."
        ]
      },
      {
        heading: "Syntactical validation",
        source: "Ch.3 p.7-p.9",
        bullets: [
          "Syntactical validation checks format or syntax.",
          "Email example: check for @, a valid top-level domain such as .com, .net, or .org, allowed domain characters, and reasonable length.",
          "Email length rules from the slides: local part before @ should be no more than 63 characters; total email length should be no more than 254 characters.",
          "Dangerous characters named in the slides: backticks, single quotes, double quotes, and null bytes.",
          "Backticks can execute shell commands in Linux or Unix shells if input is passed into a shell command.",
          "Single quotes can break SQL strings and enable SQL injection patterns such as OR conditions.",
          "Double quotes can break out of quoted strings in languages, HTML, SQL, or attributes.",
          "Null bytes can make programs think a string ends early, causing path manipulation such as treating evil.php\\0.jpg as evil.php.",
          "Best email validation approach from the slides: do basic syntax validation first, then pass the address to the mail server and catch rejection as a semantic check."
        ]
      },
      {
        heading: "Semantic validation",
        source: "Ch.3 p.10-p.12",
        bullets: [
          "Semantic validation checks whether input makes sense for the application's business rules and logic.",
          "Age example: if the application expects ages 18 to 100, a value outside that range may be syntactically numeric but semantically invalid.",
          "Email legitimacy example: send an email and require the user to click a link or enter a code.",
          "The slide says verification tokens or codes should be at least 32 characters long and time limited, such as expiring after eight hours.",
          "After email ownership is validated, the user should authenticate through the normal mechanism.",
          "Semantic validation helps reject data that is technically valid but meaningless in context."
        ]
      },
      {
        heading: "Prevention measures for secure input",
        source: "Ch.3 p.13-p.14",
        bullets: [
          "Use prepared statements or parameterized queries to prevent SQL injection.",
          "Use input encoding, such as HTML encoding, to convert input into a safer format and reduce SQL injection and XSS risk.",
          "Check buffer sizes and reject values larger than the allocated buffer to avoid memory corruption and possible remote code execution.",
          "Apply access controls and privilege management to limit the impact of input-related attacks.",
          "Hide raw database errors from users.",
          "Use a Web Application Firewall (WAF).",
          "Keep software and frameworks updated, including Python, PHP, and MySQL."
        ]
      },
      {
        heading: "SQL injection",
        source: "Ch.3 p.15-p.27",
        bullets: [
          "SQL injection happens when SQL code is inserted or appended into application or user input parameters and later passed to a back-end SQL server for parsing and execution.",
          "If an attacker modifies an SQL statement, it runs with the same rights as the application user.",
          "If SQL server commands interact with the operating system, the process runs with the permissions of the component that executed it, such as database server, application server, or web server.",
          "Database-driven web applications are common because they pull information such as product information, stock levels, prices, and shipping costs.",
          "Bad coding example: building a query by concatenating user input into SELECT * FROM users WHERE name = 'user input'.",
          "Attack example: John' OR '1'='1 makes the condition always true, so the attacker may see all users without proper authentication.",
          "Safer solution: a parameterized query uses a placeholder, so the database treats the input as a value, not executable SQL code.",
          "Prepared statement example: prepare SELECT * FROM students WHERE name = ? and execute it with the user's name.",
          "URL example: products.php?val=100 can be abused if val is directly placed into SELECT * FROM products WHERE id=$val.",
          "Tampered URL example from the slides uses OR '1'='1, which may show all data, crash the application, or leak technical details through bad error messages.",
          "Login example: UNION SELECT is used to combine results and expose CreditCardData on a login success page. The slide explains that UNION combines both query results."
        ]
      },
      {
        heading: "Prevent sensitive data exposure",
        source: "Ch.3 p.28-p.30",
        bullets: [
          "Do not store sensitive information that is not required.",
          "Classify data that the application processes, stores, or transmits.",
          "Identify sensitive data according to privacy laws or business needs.",
          "Encrypt all sensitive data stored by the application.",
          "Use strong and updated standard algorithms, protocols, and keys.",
          "Protect data in transit between the user and the service, between data centers, and end-to-end between users.",
          "The chapter summary emphasizes input filtering, sanitization, encoding, prepared statements, TLS, encryption at rest and in transit, and access control."
        ]
      }
    ],
    memory: [
      "T-U input: Trusted or Untrusted. Treat web and external input as untrusted.",
      "FSN: Filtering, Sanitization, Normalization.",
      "Syntax asks: Is it shaped right? Semantic asks: Does it make sense here?",
      "SAFE input: Sort source, Allow valid patterns, Fix or clean input, Execute with parameters.",
      "SQL defense anchor: placeholders make input data, not code."
    ],
    flashcards: [
      ["What is syntactical validation?", "Checking whether input follows the expected format or syntax."],
      ["What is semantic validation?", "Checking whether input makes sense under the application's business rules."],
      ["What are filtering, sanitization, and normalization?", "Filtering accepts only good input, sanitization cleans dirty input, and normalization makes input consistent."],
      ["Why do parameterized queries stop SQL injection?", "The placeholder tells the database the input is a value, not SQL code."],
      ["What sensitive data should be stored?", "Only sensitive data that is required; unwanted sensitive data should not be stored."]
    ],
    quiz: [
      {
        question: "Which validation type checks whether an email has the right format?",
        options: ["Semantic", "Syntactical", "Operational", "Residual"],
        answer: 1,
        explain: "Syntactical validation checks format, such as email structure."
      },
      {
        question: "Which measure directly prevents SQL injection in the slides?",
        options: ["More colorful error pages", "Prepared statements or parameterized queries", "Longer comments", "Public database errors"],
        answer: 1,
        explain: "Prepared statements and parameterized queries are repeated as SQL injection defenses."
      },
      {
        question: "What does input normalization do?",
        options: ["Makes input consistent", "Deletes the database", "Shows raw errors", "Disables access control"],
        answer: 0,
        explain: "Normalization makes input consistent before processing."
      }
    ]
  },
  {
    id: "ch4",
    number: "04",
    title: "Static Analysis Framework",
    source: "Chapter 4, 21 slides",
    summary:
      "This chapter covers static analysis as early code inspection without execution, including tools, analysis models, rules, reports, benefits, limitations, and selection factors.",
    sections: [
      {
        heading: "Static analysis definition and purpose",
        source: "Ch.4 p.2-p.5",
        bullets: [
          "Static analysis helps detect security issues early in development before code is deployed to production.",
          "It identifies potential vulnerabilities before attackers can exploit them.",
          "Static analysis means analyzing software without executing it.",
          "It is used to find potential errors or weaknesses in source code.",
          "It can find vulnerabilities, improve code quality, and support compliance with coding standards."
        ]
      },
      {
        heading: "Tools and frameworks",
        source: "Ch.4 p.5-p.12",
        bullets: [
          "Frameworks named in the slides include SonarQube, Coverity, Checkmarx, and Semgrep.",
          "SonarQube is an open-source platform with dashboards for tracking and analyzing code quality and security issues. It supports many languages and integrates with development tools.",
          "Coverity is a commercial static analysis tool for C, C++, Java, and other languages. It is used in safety and security critical industries such as aerospace, defense, and automotive.",
          "Checkmarx is a commercial static analysis tool for more than 20 languages, including Java, .NET, and PHP. It is often used where compliance and security matter, such as finance, healthcare, and government.",
          "Semgrep scans source code without running it to find bugs, vulnerabilities, and code quality issues. The slides say it works with 30+ languages including Python."
        ]
      },
      {
        heading: "Analysis models",
        source: "Ch.4 p.5, p.13-p.14",
        bullets: [
          "Static analysis frameworks use models such as control flow models, data flow models, and abstract syntax trees.",
          "The choice of model depends on the required analysis.",
          "Data Flow Analysis is useful for security vulnerabilities such as injection attacks.",
          "Control Flow Analysis is useful for execution paths and possible deadlocks.",
          "Abstract Syntax Trees are useful for syntax errors and coding standards because they represent the structure of code."
        ]
      },
      {
        heading: "Rules, reporting, benefits, and limits",
        source: "Ch.4 p.15-p.20",
        bullets: [
          "Static analysis frameworks use algorithms and rules designed to identify specific errors or weaknesses.",
          "Results may be reported as graphics, lists, or detailed reports.",
          "Benefits: find vulnerabilities before deployment, improve code quality and maintainability, detect source-level issues that may be difficult to find by other tests, speed development, and reduce security incident risk.",
          "Limitations: may miss vulnerabilities, may create false positives, cannot detect issues caused by runtime behavior or system interactions.",
          "Static analysis should be complemented with dynamic analysis, penetration testing, and code reviews.",
          "Selection factors include cost, ease of use, required expertise, and integration with development or bug tracking tools.",
          "Example static analysis rules include buffer overflow detection, code complexity analysis, SQL injection detection, XSS detection, and memory leak detection.",
          "Understanding results is critical because false positives and false negatives can occur."
        ]
      }
    ],
    memory: [
      "Static = scan without starting the program.",
      "DCA models: Data flow, Control flow, AST.",
      "RRF workflow: Rules run, Results reported, Fixes follow.",
      "FP/FN: False Positive is flagged but safe; False Negative is missed but risky."
    ],
    flashcards: [
      ["What is static analysis?", "Analyzing source code without executing the software."],
      ["Which model helps find injection-style vulnerabilities?", "Data Flow Analysis."],
      ["Why should static analysis be combined with other testing?", "It can miss runtime and system interaction issues and can produce false positives or false negatives."],
      ["Name two static analysis tools from the slides.", "Examples include SonarQube, Coverity, Checkmarx, and Semgrep."]
    ],
    quiz: [
      {
        question: "Which statement is true about static analysis?",
        options: ["It runs the program in production", "It analyzes code without executing it", "It replaces all testing", "It only works on web pages"],
        answer: 1,
        explain: "Static analysis inspects software without running it."
      },
      {
        question: "Which model is useful for syntax errors and coding standards?",
        options: ["Abstract Syntax Tree", "Session ID", "DREAD", "BOLA"],
        answer: 0,
        explain: "The slides say ASTs are useful for syntax errors and coding standards."
      },
      {
        question: "What is a false negative in static analysis?",
        options: ["A safe issue flagged as vulnerable", "A vulnerability that the tool fails to detect", "A successful deployment", "A compliance report"],
        answer: 1,
        explain: "False negatives are missed vulnerabilities."
      }
    ]
  },
  {
    id: "ch5",
    number: "05",
    title: "Buffer Overflow",
    source: "Chapter 5, 17 slides",
    summary:
      "This chapter explains memory buffers, how overflows happen, warning signs, root causes, impact, stack behavior, analysis tools, and prevention at code, compiler, system, and process levels.",
    sections: [
      {
        heading: "What a buffer overflow is",
        source: "Ch.5 p.2-p.4",
        bullets: [
          "A buffer overflow occurs when a program writes more data to a memory buffer than it was allocated to hold.",
          "Buffers are fixed-size memory blocks used for input strings, arrays, or temporary variables.",
          "When data exceeds capacity, it overflows into adjacent memory and may overwrite valid data or program control information.",
          "Possible results include crashes, data corruption, and attacker execution of malicious code.",
          "Importance from the slides: exploitation risk, privilege escalation, data breach, and denial of service."
        ]
      },
      {
        heading: "Indicators and examples",
        source: "Ch.5 p.5-p.8",
        bullets: [
          "Code-level indicators: unsafe functions such as gets, strcpy, and scanf(\"%s\"); missing input size checks; fixed-size buffers without validation; direct pointer manipulation in C or C++.",
          "System or runtime indicators: segmentation faults, unexpected behavior after unusual input, security tools reporting memory access violations, and debuggers showing overwritten stack or heap values.",
          "Unsafe scanf example: char name[20]; scanf(\"%s\", name); reads a string with no limit. More than 20 characters can overflow.",
          "Safer scanf example: scanf(\"%19s\", name); reads at most 19 characters, leaving room for the string end marker.",
          "Unsafe strcpy example: copying a larger source string into a smaller destination buffer.",
          "Safer strncpy example: copy at most sizeof(buf) - 1 and manually add the null terminator.",
          "Python is described as safer in the slide because it creates strings of the right size, resizes as needed, and frees memory through garbage collection."
        ]
      },
      {
        heading: "Factors and root-cause analysis",
        source: "Ch.5 p.9-p.10",
        bullets: [
          "Contributing factors: lack of input validation, unsafe functions, languages without bounds checking, legacy code and poor design, software complexity, insufficient testing and review, and mismanaged dynamic memory.",
          "Root-cause analysis asks whether the overflow is stack-based or heap-based.",
          "Trace the exact input that caused the overflow.",
          "Check whether poor coding practice, lack of input validation, or mismanaged memory caused it.",
          "Impact assessment: confidentiality breach, integrity violation, availability risk, and privilege escalation.",
          "Tools named: SonarQube, Coverity, Flawfinder, Valgrind, AddressSanitizer, Purify, fuzz testing, GDB, IDA Pro, and OllyDbg."
        ]
      },
      {
        heading: "Prevention measures",
        source: "Ch.5 p.11-p.12",
        bullets: [
          "Stack canaries are special values placed next to return addresses. If overwritten, the program aborts before returning.",
          "ASLR randomizes memory addresses of stack, heap, and libraries so exploit targets are harder to predict.",
          "DEP or NX Bit marks stack or heap memory as non-executable to prevent injected shellcode from running.",
          "Runtime protection libraries such as libsafe and StackGuard detect or stop unsafe calls.",
          "Process-level controls: build security into the SSDLC, use static and dynamic analysis, fuzz, review code, and train developers continuously."
        ]
      },
      {
        heading: "Stack overflow behavior and real-world impact",
        source: "Ch.5 p.13-p.16",
        bullets: [
          "The software security stack follows LIFO: last in, first out.",
          "Normal stack: stack grows downward from high addresses to low addresses. Local variables stay within their allocated space and do not affect the return pointer.",
          "Smashed stack: too much data written into Buffer 1 spills into adjacent memory, overwrites Buffer 2 and the return pointer, and may redirect execution to injected code.",
          "Memory layout in the slide: executable code at the lowest addresses, then data segment, heap growing upward, and stack growing downward.",
          "Real-world impacts: denial of service from crash or hang, data leakage from nearby memory, arbitrary code execution by overwritten return addresses, and privilege escalation if the vulnerable program runs with admin or root rights.",
          "Chapter summary: buffer overflow means memory overrun and severe security risk; root causes are poor coding, unsafe functions, and lack of checks; identification uses tools, testing, and runtime behavior; prevention uses coding practices, compiler protections, and training."
        ]
      }
    ],
    memory: [
      "BOUND: Bounds checks, Oversized input rejected, Unsafe functions avoided, Null terminator set, Defenses enabled.",
      "CIA impact: leaks hurt Confidentiality, overwritten data hurts Integrity, crashes hurt Availability.",
      "Stack memory clue: stack grows down, heap grows up.",
      "Canary-ASLR-DEP: detect overwrite, randomize location, block execution."
    ],
    flashcards: [
      ["What is a buffer overflow?", "Writing more data to a fixed-size memory buffer than it can hold."],
      ["Why is scanf(\"%s\") risky in C?", "It reads a string without a size limit unless a width is specified."],
      ["What does ASLR do?", "It randomizes memory addresses for stack, heap, and libraries."],
      ["What happens when the return pointer is overwritten?", "Program control can jump to attacker-chosen code or instructions."]
    ],
    quiz: [
      {
        question: "Which function is named as unsafe in the buffer overflow slides?",
        options: ["strcpy", "isdigit", "UseSession", "HttpOnly"],
        answer: 0,
        explain: "gets, strcpy, and scanf(\"%s\") are listed as unsafe code-level indicators."
      },
      {
        question: "What is the purpose of a stack canary?",
        options: ["Encrypt a password", "Detect overwritten return-address area before returning", "Open a socket", "Create an audit log"],
        answer: 1,
        explain: "Stack canaries are special values placed near return addresses to detect overwrites."
      },
      {
        question: "Which impact is tied to a crash or service downtime?",
        options: ["Availability risk", "Input normalization", "Security review", "CWE mapping"],
        answer: 0,
        explain: "Crashes and downtime affect availability."
      }
    ]
  },
  {
    id: "ch6",
    number: "06",
    title: "Web Application: Broken Access Control",
    source: "Chapter 6, 47 slides",
    summary:
      "This chapter explains authorization, vertical/horizontal/context-dependent access control, common attacks, IDOR/BOLA/MFLAC/BFLA scenarios, and authorization security guidelines.",
    sections: [
      {
        heading: "Access control basics",
        source: "Ch.6 p.4-p.7",
        bullets: [
          "Access control, or authorization, applies constraints on who or what can perform actions or access requested resources.",
          "In web applications, access control depends on authentication and session management.",
          "Authentication identifies the user and confirms who they are.",
          "Session management links later HTTP requests to the same user.",
          "Access control decides whether that user is allowed to perform the attempted action.",
          "Broken access control weaknesses named in the slides: lack of proper authentication, weak passwords, insufficient authorization, and lack of auditing.",
          "Categories: vertical access control, horizontal access control, and context-dependent access control."
        ]
      },
      {
        heading: "Access control categories",
        source: "Ch.6 p.8-p.16",
        bullets: [
          "Vertical access controls apply to different hierarchy levels. Users are allowed or denied based on role or authority, such as admin versus regular user.",
          "Vertical example: admin users can reach admin resources and functions, while regular users cannot.",
          "Horizontal access controls apply across users at the same privilege level. Users can access their own resources but not another user's resources.",
          "Horizontal example: two regular users cannot access each other's resources even though they share the same privilege level.",
          "Context-dependent access controls apply based on context such as location, time, device, network, workflow, or action order.",
          "Context example: an e-commerce site should prevent users from modifying cart contents after payment. The user cannot perform actions in the wrong order."
        ]
      },
      {
        heading: "Common attacks",
        source: "Ch.6 p.17-p.29",
        bullets: [
          "Admin page access: a normal user may browse directly to admin URLs such as /admin, /administrator, or /web_admin. Successful access generally causes vertical privilege escalation.",
          "Directory traversal file include: weak input validation can let attackers read or write files that should not be accessible.",
          "ACLs define which users or groups can access, modify, or execute a file and are designed to prevent sensitive file access.",
          "Local File Inclusion (LFI): the app lets a user include a local file by passing a path in a request parameter. Attackers may use .. to move up directories. Example path target from the slide: ../../../../etc/passwd.",
          "Remote File Inclusion (RFI): the app includes a remote file from a user-supplied URL, such as a file hosted on the attacker's server.",
          "Phishing: attackers pretend to be a trusted entity to trick victims into giving passwords, credit card numbers, or other sensitive information.",
          "Phishing types shown: email phishing, spear phishing, angler phishing, smishing and vishing, clone phishing, and phone phishing.",
          "Spoofing: attackers falsify information to look like a trusted source, such as email address, IP address, or website.",
          "Spoofing types shown: email spoofing, IP spoofing, DNS server spoofing, caller ID spoofing, and website spoofing.",
          "Spoofing versus phishing table: spoofing focuses on stealing identity to act as another individual; phishing focuses on stealing sensitive user information. Spoofing can be part of phishing, but phishing is not part of spoofing."
        ]
      },
      {
        heading: "IDOR and BOLA",
        source: "Ch.6 p.30-p.36",
        bullets: [
          "Real-world scenarios named: IDOR, BOLA, MFLAC, and BFLA.",
          "IDOR means Insecure Direct Object Reference. It occurs when an application gives direct object access based on user-supplied input such as an ID or key.",
          "IDOR lets attackers bypass authorization and access system resources such as database records or files.",
          "E-commerce example: user should only see their own cart, but the URL contains userID=1234. If changing it to userID=5678 shows another user's cart, IDOR exists.",
          "Impact examples from the slides: changing address, changing payment method, deleting the account.",
          "BOLA means Broken Object Level Authorization. The slides define it as IDOR in APIs.",
          "BOLA risk exists because APIs expose endpoints that handle object identifiers. Object-level authorization checks should be in every function that accesses a data source using user input.",
          "API example shown: GET /api/userInfo/1234 returns name, address, email, and credit card data. If changing only the user ID fetches another user's data, sensitive information is disclosed."
        ]
      },
      {
        heading: "MFLAC and BFLA",
        source: "Ch.6 p.37-p.43",
        bullets: [
          "MFLAC means Missing Function Level Access Control.",
          "Applications should verify function-level access rights for every requested action by every user.",
          "If checks are missing, users may reach critical areas without authorization.",
          "Slide example: users may be allowed to POST /account/edit.php, but not delete accounts. If POST /account/delete.php succeeds for a normal user, MFLAC exists.",
          "BFLA means Broken Function Level Authorization.",
          "BFLA is encouraged by complex access control policies, many hierarchies, groups and roles, and unclear separation between admin and regular functions.",
          "By exploiting BFLA, attackers gain access to other users' resources or administrative functions.",
          "Tampering example shown: original GET /api/users/v1/user/myinfo is changed to GET /api/admins/v1/users/all."
        ]
      },
      {
        heading: "Remediation and authorization security",
        source: "Ch.6 p.44-p.46",
        bullets: [
          "Access control vulnerabilities do not have one simple formula because rights, permissions, principles, context, workflow, and application purpose vary.",
          "Do not rely on obfuscation.",
          "Deny access by default.",
          "Use one application-wide access control mechanism consistently across modules.",
          "Continuously audit and test access control.",
          "Minimize CORS usage. The slide explains Same-Origin Policy as: a web page can only make requests to the same domain it loaded from.",
          "Disable web server directory listing.",
          "Log and alert.",
          "Rate limit APIs.",
          "Force all requests through access control checks.",
          "Give as least or as little necessary access as possible."
        ]
      }
    ],
    memory: [
      "Access chain: Auth identifies, Session remembers, Access decides.",
      "VHC controls: Vertical, Horizontal, Context-dependent.",
      "Object issues: IDOR in pages, BOLA in APIs.",
      "Function issues: MFLAC means missing checks; BFLA means broken role/function authorization.",
      "Authorization safe set: Deny by default, one mechanism, audit/test, log/alert, rate limit, least access."
    ],
    flashcards: [
      ["What is access control?", "Rules that decide who or what may perform actions or access requested resources."],
      ["What is vertical access control?", "Access control by hierarchy or authority level, such as admin versus regular user."],
      ["What is IDOR?", "Direct object access based on user input that lets attackers bypass authorization."],
      ["How do the slides describe BOLA?", "IDOR in APIs."],
      ["What should every request pass through?", "Access control checks."]
    ],
    quiz: [
      {
        question: "Which access control stops one regular user from viewing another regular user's cart?",
        options: ["Vertical", "Horizontal", "Context-dependent", "Static"],
        answer: 1,
        explain: "Horizontal access control separates users at the same privilege level."
      },
      {
        question: "What does BOLA mean in the slides?",
        options: ["Buffer Object Level Audit", "Broken Object Level Authorization", "Basic Online Login Attack", "Blocked Object Login Access"],
        answer: 1,
        explain: "BOLA is Broken Object Level Authorization and is described as IDOR in APIs."
      },
      {
        question: "Which guideline is listed under Authorization Security?",
        options: ["Rely on hidden URLs", "Deny access by default", "Show directory listings", "Ignore API rate limits"],
        answer: 1,
        explain: "Deny access by default is explicitly listed."
      }
    ]
  },
  {
    id: "ch7",
    number: "07",
    title: "Error and Exception",
    source: "Chapter 7, 42 slides",
    summary:
      "This chapter covers return codes, exception handling, exception classification, resource leaks, logging, debugging, and secure practices that avoid crashes, data leakage, and denial of service.",
    sections: [
      {
        heading: "Why error and exception handling matters",
        source: "Ch.7 p.3",
        bullets: [
          "Error and exception handling is critical to software security.",
          "Improper handling can cause crashes, denial of service, or attacker exploitation.",
          "Secure software handles errors gracefully, prevents information leakage, and releases resources correctly."
        ]
      },
      {
        heading: "Return codes",
        source: "Ch.7 p.4-p.10",
        bullets: [
          "Return codes are common in C, C++, and system-level code.",
          "A function returns a special value such as -1, NULL, or an error constant instead of stopping execution.",
          "The caller must check and handle the return code.",
          "Normal return means success. Error return is a distinct value for a problem.",
          "Examples: 0 means success, -1 means failure, NULL means invalid pointer or resource unavailable.",
          "Three categories: programmer-defined return codes, existing server or HTTP status codes, and existing OS return codes such as Linux or UNIX.",
          "HTTP examples from the slides: 404 Page Not Found, 403 Forbidden, 500 Internal Server Error, 200 OK.",
          "Linux/UNIX examples: 0 success, 1 general error, 2 misuse of shell built-in or command, 126 command invoked cannot execute, 127 command not found, 128 invalid argument to exit, 130 script terminated by Control-C, 255 exit status out of range.",
          "Advantages: simple, efficient, no advanced exception mechanism needed, predictable in embedded or OS programming.",
          "Security concerns: ignored return values, inconsistent or ambiguous codes, information leakage from detailed codes, and messy manual error propagation.",
          "Best practices: always check return values, standardize codes, document values clearly, avoid exposing sensitive details, and combine with logging."
        ]
      },
      {
        heading: "Exceptions and secure handling",
        source: "Ch.7 p.11-p.19",
        bullets: [
          "Exceptions are events that disrupt normal execution.",
          "They separate normal logic from error-handling logic and are used in Java, Python, C#, and C++.",
          "Exception handling detects, raises, and handles abnormal conditions.",
          "Try block: code that may cause an error.",
          "Catch block: handles the error.",
          "Finally block: cleanup code such as releasing resources.",
          "Advantages: cleaner code, flexibility, scalability, and centralized handling.",
          "Security risks of poor exception handling: unhandled exceptions cause crashes and DoS; overly generic catch blocks hide real issues; detailed messages reveal sensitive info; silent failures hide attacks.",
          "Best practices: catch specific exceptions, never show stack traces or internals to users, log exceptions securely for admins, use finally or try-with-resources to release resources, and create custom exception classes for clarity.",
          "Secure example notes: a file open operation should close the file automatically, handle missing files and permission errors, log detailed errors for administrators, show user-friendly messages, and always run cleanup."
        ]
      },
      {
        heading: "Return codes versus exceptions",
        source: "Ch.7 p.19",
        bullets: [
          "Return codes are lightweight and work without exception support.",
          "Return code risks: easy to forget checks, inconsistent codes, messy propagation, and detailed codes may leak sensitive information.",
          "Exceptions make code cleaner, centralize error management, and handle multiple error types more easily.",
          "Exception risks: unhandled exceptions can crash programs, generic catch blocks can hide real problems, and verbose error messages can reveal system details.",
          "Use return codes for low-level system calls, embedded software, and performance-critical code.",
          "Use exceptions for high-level application logic and complex systems needing maintainability and security."
        ]
      },
      {
        heading: "Classification of exceptions",
        source: "Ch.7 p.20-p.25",
        bullets: [
          "Classifying exceptions helps developers design better error handling strategies.",
          "Checked exceptions must be handled at compile time in languages like Java. Examples: IOException and SQLException.",
          "Checked exceptions force developers to anticipate recoverable errors and support safer coding.",
          "Unchecked exceptions happen at runtime and are not forced by the compiler. Examples: NullPointerException and ArrayIndexOutOfBoundsException.",
          "Unchecked exceptions often come from programming errors. Attackers may exploit unhandled runtime exceptions to crash applications.",
          "System exceptions or fatal errors relate to runtime environment or system resources. Examples: OutOfMemoryError and StackOverflowError.",
          "System exceptions may come from resource exhaustion, infinite loops, or memory leaks and can cause denial of service.",
          "Additional sub-classifications: application-defined exceptions, recoverable exceptions such as file not found, and non-recoverable exceptions such as memory corruption.",
          "Security implications: checked exceptions encourage defensive coding; unchecked exceptions need secure programming; system exceptions need fail-safe defaults such as safe shutdown and logging."
        ]
      },
      {
        heading: "Resource leaks",
        source: "Ch.7 p.26-p.33",
        bullets: [
          "A resource leak happens when a program acquires memory, file handles, sockets, database connections, or similar resources but fails to release them.",
          "Resource leaks are common in long-running applications and can cause performance degradation, instability, or crashes.",
          "Attackers may exploit resource leaks for denial of service.",
          "The slide notes that a resource leak does not leak confidential data; it leaks system resources and affects availability.",
          "Resource examples: heap memory, open file handles, network sockets, database connections, threads, and processes.",
          "C example issue: a file opened without fclose creates a leak. Each call allocates a handle, and missing fclose can exhaust descriptors.",
          "Prevention techniques: structured cleanup with finally, automatic resource management with Java try-with-resources or Python with, RAII, monitoring and logging, profiling tools, defensive programming, NULL after free, timeouts, and connection pools with maximum limits."
        ]
      },
      {
        heading: "Logging and debugging",
        source: "Ch.7 p.34-p.42",
        bullets: [
          "Logging records events, errors, and system activity for later analysis.",
          "Debugging identifies, analyzes, and fixes bugs.",
          "Together, logging and debugging support incident response, auditing, and forensics.",
          "Logging purposes: monitor normal and abnormal activities, detect intrusions or suspicious behavior, provide investigation evidence, and support compliance such as ISO 27001 and PCI DSS.",
          "Log types: system logs, application logs, security logs, and audit logs.",
          "Logging risks: sensitive data exposure, log injection, log tampering, and over-logging.",
          "Secure logging practices: never log passwords or encryption keys, use levels DEBUG/INFO/WARN/ERROR/FATAL, make logs tamper-proof, encrypt and securely store sensitive logs, and monitor logs in real time with SIEM systems such as Splunk or ELK.",
          "Debugging purposes: identify root causes, test security assumptions, and validate behavior under edge cases.",
          "Debugging techniques: print or trace debugging, interactive debugging with tools such as GDB or Visual Studio Debugger, remote debugging, and automated tools such as static analysis, dynamic analysis, and fuzz testing.",
          "Debugging risks: debug code left in production, verbose error messages, and temporary backdoors.",
          "Secure debugging practices: disable debugging in production, limit debug tool access to authorized developers, sanitize user-facing error messages, and use logs to guide debugging.",
          "Golden rule from the slides: never expose internal error details to users; log securely for administrators."
        ]
      }
    ],
    memory: [
      "Return code habit: Check, Standardize, Document, Hide details, Log.",
      "TCF model: Try risky code, Catch the specific issue, Finally clean up.",
      "Exception classes: Checked, Unchecked, System.",
      "CLF for secure errors: Close resources, Log securely, Friendly user message.",
      "Logs need FCL: Fit log level, Control access, Lock against tampering."
    ],
    flashcards: [
      ["What is a return code?", "A special return value that signals success or failure to the caller."],
      ["What does a finally block do?", "Runs cleanup code such as releasing resources."],
      ["Why are verbose error messages risky?", "They may reveal system internals to attackers."],
      ["What is a resource leak?", "A resource is acquired but not released properly."],
      ["What is the golden rule for errors in this chapter?", "Never expose internal error details to users; log securely for administrators."]
    ],
    quiz: [
      {
        question: "Which HTTP status code means Forbidden in the slides?",
        options: ["200", "403", "404", "500"],
        answer: 1,
        explain: "403 is shown as Forbidden."
      },
      {
        question: "Which exception category is checked at compile time in Java?",
        options: ["Checked exceptions", "Unchecked exceptions", "System exceptions", "Audit exceptions"],
        answer: 0,
        explain: "Checked exceptions must be handled at compile time."
      },
      {
        question: "Which logging practice is secure?",
        options: ["Log passwords for convenience", "Make logs tamper-proof and restrict access", "Show stack traces to users", "Keep debug mode on in production"],
        answer: 1,
        explain: "Secure logging uses tamper-proof storage and restricted access."
      }
    ]
  },
  {
    id: "ch8",
    number: "08",
    title: "Broken Authentication",
    source: "Chapter 8, 41 slides",
    summary:
      "This chapter explains authentication versus authorization, authentication factors, broken authentication categories, attacks, session problems, password storage, account recovery, MFA, and awareness.",
    sections: [
      {
        heading: "Authentication and authorization",
        source: "Ch.8 p.3-p.6",
        bullets: [
          "Authentication verifies that you are who you say you are by passing credentials such as username and password across identity and directory systems.",
          "Authorization gives someone permission to do or have something. The administrator specifies which users have system access and which privileges each user has.",
          "Authentication factors: something you have, something you know, and something you are.",
          "Something you have: a unique object such as access card or key fob. It avoids forgotten passwords but can be lost or stolen.",
          "Something you know: confidential information such as login and password.",
          "Something you are: biometric characteristics such as fingerprint, voice, or iris pattern. Harder to lose or copy, but can be expensive and less accurate than traditional factors."
        ]
      },
      {
        heading: "What broken authentication is",
        source: "Ch.8 p.7-p.10",
        bullets: [
          "Broken authentication refers to weaknesses in an online platform or application that let hackers bypass login security and gain the privileges of the hacked user.",
          "Two main vulnerability categories cause broken authentication: session management vulnerabilities and credential management vulnerabilities.",
          "Session ID is created and assigned when a user logs in. It tracks what the user does and helps the site respond.",
          "If an attacker gets the session ID while the user is logged in, it is essentially as good as having the password. The attacker can impersonate the user.",
          "Credential management vulnerabilities happen when a site fails to protect users from attackers using hacked or stolen passwords."
        ]
      },
      {
        heading: "Examples of broken authentication",
        source: "Ch.8 p.11-p.23",
        bullets: [
          "Examples named: password spraying, credential stuffing, session hijacking, session ID URL, and phishing attacks.",
          "Password spraying: attackers try simple weak passwords such as 12345 or password across accounts.",
          "The weak password table includes examples such as 123456, 123456789, qwerty, password, 111111, 12345678, abc123, 1234567, password1, 1234567890, 123123, 12345, iloveyou, 666666, 123, monkey, dragon, 1qaz2wsx, 123qwe, 121212, myspace, a123456, qwe123, zxcvbnm, 7777777, 123abc, and qwerty123.",
          "Credential stuffing: stolen usernames or emails and passwords, often from breaches, are used in automated login requests against a web application.",
          "Session hijacking: an attacker takes over a user session. It relies on knowing the session cookie and is also called cookie hijacking or cookie side-jacking.",
          "The XSS session hijacking illustration shows: attacker injects script, victim authenticates, server returns page code with injected script, the browser executes it and sends the session cookie to the attacker, then the attacker hijacks the session.",
          "Session ID URL: a server creates a session ID and stores it in a cookie, but the ID may also be appended to the URL as a parameter.",
          "Shopping cart example: the session ID keeps the cart from being lost and associates products with the session cookie.",
          "Example URL with a session ID: https://www.example.com/index.php?sid=123454321abcde-54321dcba.",
          "Phishing attack: malicious actors send messages pretending to be trusted people or entities, pushing users to install malicious files, click harmful links, or disclose credentials. Channels include email, messaging apps, and SMS."
        ]
      },
      {
        heading: "Secure password storage vulnerabilities",
        source: "Ch.8 p.24-p.28",
        bullets: [
          "Secure password storage is important because passwords are often the first line of defense against unauthorized access.",
          "Plain-text password storage is the most basic vulnerability because anyone with storage access can read passwords.",
          "Weak password hashing is vulnerable to brute force or dictionary attacks.",
          "Inadequate salt usage weakens password protection. Salt should be unique and random before hashing.",
          "Password recovery mechanisms such as email reset links can be abused if not secured. If an attacker gets the user's email, they may use reset links.",
          "Insider attacks are a threat when employees or contractors with access abuse access or leak information."
        ]
      },
      {
        heading: "How to address broken authentication",
        source: "Ch.8 p.29-p.39",
        bullets: [
          "Do not allow weak passwords. Require length, special characters, letters, and numbers so the system rejects weak choices.",
          "Slide configuration example requires a digit, required length 8, non-alphanumeric character, uppercase, lowercase, and required unique characters.",
          "Add a strict credential recovery process with several verification checks and steps, making abuse difficult and costly.",
          "Slide recovery configuration includes 30-minute lockout, 10 maximum failed attempts, confirmed email, and unique email.",
          "Implement breached password protection: lock accounts whose passwords are known to be compromised, and restore access when users change passwords.",
          "Regulate session length: end sessions after inactivity. Sensitive banking should have a shorter timeout than a streaming platform.",
          "Improve session management: issue individual session IDs after each successful authentication and invalidate old session IDs when sessions end.",
          "Do not use session ID URLs. The slides say secure web URLs with SSL without including the session ID.",
          "Use MFA. The slide example is an OTP sent by email or message.",
          "Awareness: educate users regularly about phishing and weak password risks, such as monthly or quarterly reminder emails."
        ]
      },
      {
        heading: "Testing tools and summary",
        source: "Ch.8 p.40-p.41",
        bullets: [
          "Testing tools named: WebGoat for education and Pentest-Tools.com for real-world testing.",
          "Chapter summary: broken authentication is a security vulnerability where authentication methods are weak, easily guessable, bypassable, or sensitive information is stored or transmitted insecurely."
        ]
      }
    ],
    memory: [
      "HKA factors: Have, Know, Are.",
      "Session rule: a stolen session ID can act like a stolen password.",
      "Five attack examples: spraying, stuffing, hijacking, session ID URL, phishing.",
      "Password storage risk list: plain text, weak hash, weak salt, weak recovery, insider.",
      "Auth repair list: strong passwords, strict recovery, breached-password protection, session timeout, session invalidation, no session IDs in URLs, MFA, awareness."
    ],
    flashcards: [
      ["What is authentication?", "Verifying that a user is who they claim to be."],
      ["What is authorization?", "Giving permission to access systems or perform actions."],
      ["Why is a stolen session ID dangerous?", "It can let the attacker impersonate the logged-in user."],
      ["What is credential stuffing?", "Using stolen username/password lists in automated login attempts."],
      ["Name the three authentication factors.", "Something you have, something you know, and something you are."]
    ],
    quiz: [
      {
        question: "Which item is an authentication factor from the slides?",
        options: ["Something you have", "Something you compile", "Something you deploy", "Something you audit"],
        answer: 0,
        explain: "The factors are something you have, know, and are."
      },
      {
        question: "What does credential stuffing use?",
        options: ["Only brand-new passwords", "Stolen username/password lists and automated login requests", "Compiler warnings", "Directory traversal paths"],
        answer: 1,
        explain: "Credential stuffing uses stolen credentials against web applications at scale."
      },
      {
        question: "Which is a recommended broken-authentication defense?",
        options: ["Put session IDs in URLs", "Never expire sessions", "Use MFA", "Store passwords in plain text"],
        answer: 2,
        explain: "MFA is listed as a protection mechanism."
      }
    ]
  }
];

const chapterNav = document.querySelector("#chapterNav");
const content = document.querySelector("#content");
const chapterTitle = document.querySelector("#chapterTitle");
const chapterSource = document.querySelector("#chapterSource");
const chapterSummary = document.querySelector("#chapterSummary");
const searchInput = document.querySelector("#searchInput");
const markCompleteBtn = document.querySelector("#markCompleteBtn");
const tabs = [...document.querySelectorAll(".tab")];

const state = {
  chapterIndex: 0,
  view: "notes",
  flashIndex: 0,
  flashRevealed: false,
  quizIndex: 0,
  quizScore: 0,
  quizAnswered: false,
  completed: new Set(JSON.parse(localStorage.getItem("completedChapters") || "[]"))
};

function saveCompleted() {
  localStorage.setItem("completedChapters", JSON.stringify([...state.completed]));
}

function escapeHtml(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function highlight(value) {
  const safe = escapeHtml(value);
  const query = searchInput.value.trim();
  if (!query) return safe;
  const escaped = query.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return safe.replace(new RegExp(escaped, "gi"), (match) => `<mark>${match}</mark>`);
}

function sectionMatches(section, query) {
  if (!query) return true;
  const haystack = `${section.heading} ${section.source} ${section.bullets.join(" ")}`.toLowerCase();
  return haystack.includes(query.toLowerCase());
}

function renderNav() {
  chapterNav.innerHTML = "";
  chapters.forEach((chapter, index) => {
    const button = document.createElement("button");
    button.type = "button";
    button.className = `chapter-btn ${index === state.chapterIndex ? "active" : ""} ${state.completed.has(chapter.id) ? "completed" : ""}`;
    button.innerHTML = `
      <span class="chapter-num">${chapter.number}</span>
      <span class="chapter-name">${escapeHtml(chapter.title)}</span>
      <span class="done-dot" aria-hidden="true"></span>
    `;
    button.addEventListener("click", () => {
      state.chapterIndex = index;
      state.flashIndex = 0;
      state.flashRevealed = false;
      state.quizIndex = 0;
      state.quizScore = 0;
      state.quizAnswered = false;
      render();
    });
    chapterNav.appendChild(button);
  });
}

function currentChapter() {
  return chapters[state.chapterIndex];
}

function renderHeader() {
  const chapter = currentChapter();
  chapterSource.textContent = chapter.source;
  chapterTitle.textContent = chapter.title;
  chapterSummary.textContent = chapter.summary;
  markCompleteBtn.textContent = state.completed.has(chapter.id) ? "Chapter studied" : "Mark chapter studied";
}

function renderNotes() {
  const chapter = currentChapter();
  const query = searchInput.value.trim();
  const sections = chapter.sections.filter((section) => sectionMatches(section, query));
  if (!sections.length) {
    content.innerHTML = `<div class="empty-state">No notes matched "${escapeHtml(query)}" in this chapter.</div>`;
    return;
  }
  content.innerHTML = `<div class="content-grid"></div>`;
  const grid = content.querySelector(".content-grid");
  sections.forEach((section) => {
    const card = document.createElement("article");
    card.className = "note-card";
    card.innerHTML = `
      <span class="source">${highlight(section.source)}</span>
      <h3>${highlight(section.heading)}</h3>
      <ul>${section.bullets.map((item) => `<li>${highlight(item)}</li>`).join("")}</ul>
    `;
    grid.appendChild(card);
  });
}

function renderMemory() {
  const chapter = currentChapter();
  content.innerHTML = `
    <div class="memory-card">
      <span class="source">${escapeHtml(chapter.source)}</span>
      <h3>Memory aids for ${escapeHtml(chapter.title)}</h3>
      <p>These short forms are made only from the chapter lists and concepts, to make recall easier.</p>
      <ul>${chapter.memory.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>
    </div>
  `;
}

function renderFlashcards() {
  const chapter = currentChapter();
  const deck = chapter.flashcards;
  const card = deck[state.flashIndex % deck.length];
  content.innerHTML = `
    <div class="flashcard ${state.flashRevealed ? "revealed" : ""}">
      <div class="source">Card ${state.flashIndex + 1} of ${deck.length}</div>
      <div class="question">${escapeHtml(card[0])}</div>
      <div class="answer">${escapeHtml(card[1])}</div>
      <div class="card-actions">
        <button class="tool-btn" id="prevCard" type="button">Previous</button>
        <button class="tool-btn" id="revealCard" type="button">${state.flashRevealed ? "Hide answer" : "Reveal answer"}</button>
        <button class="tool-btn" id="nextCard" type="button">Next</button>
      </div>
    </div>
  `;
  document.querySelector("#prevCard").addEventListener("click", () => {
    state.flashIndex = (state.flashIndex - 1 + deck.length) % deck.length;
    state.flashRevealed = false;
    renderFlashcards();
  });
  document.querySelector("#revealCard").addEventListener("click", () => {
    state.flashRevealed = !state.flashRevealed;
    renderFlashcards();
  });
  document.querySelector("#nextCard").addEventListener("click", () => {
    state.flashIndex = (state.flashIndex + 1) % deck.length;
    state.flashRevealed = false;
    renderFlashcards();
  });
}

function renderQuiz() {
  const chapter = currentChapter();
  const quiz = chapter.quiz;
  const item = quiz[state.quizIndex % quiz.length];
  content.innerHTML = `
    <div class="quiz-card">
      <span class="source">Question ${state.quizIndex + 1} of ${quiz.length} | Score ${state.quizScore}</span>
      <h3>${escapeHtml(item.question)}</h3>
      <div class="option-grid">
        ${item.options.map((option, index) => `<button class="option-btn" data-index="${index}" type="button">${escapeHtml(option)}</button>`).join("")}
      </div>
      <div class="quiz-feedback" id="quizFeedback"></div>
      <div class="quiz-actions">
        <button class="tool-btn" id="nextQuestion" type="button">Next question</button>
        <button class="tool-btn" id="resetQuiz" type="button">Reset quiz</button>
      </div>
    </div>
  `;
  document.querySelectorAll(".option-btn").forEach((button) => {
    button.addEventListener("click", () => {
      if (state.quizAnswered) return;
      state.quizAnswered = true;
      const picked = Number(button.dataset.index);
      const correct = picked === item.answer;
      if (correct) state.quizScore += 1;
      document.querySelectorAll(".option-btn").forEach((optionButton) => {
        const isAnswer = Number(optionButton.dataset.index) === item.answer;
        optionButton.classList.toggle("correct", isAnswer);
        optionButton.classList.toggle("wrong", Number(optionButton.dataset.index) === picked && !correct);
      });
      document.querySelector("#quizFeedback").textContent = `${correct ? "Correct." : "Not quite."} ${item.explain}`;
    });
  });
  document.querySelector("#nextQuestion").addEventListener("click", () => {
    state.quizIndex = (state.quizIndex + 1) % quiz.length;
    state.quizAnswered = false;
    renderQuiz();
  });
  document.querySelector("#resetQuiz").addEventListener("click", () => {
    state.quizIndex = 0;
    state.quizScore = 0;
    state.quizAnswered = false;
    renderQuiz();
  });
}

function riskLabel(score) {
  if (score >= 180) return "High";
  if (score >= 75) return "Medium";
  return "Low";
}

function renderTools() {
  const checklistKey = `checklist-${currentChapter().id}`;
  const saved = new Set(JSON.parse(localStorage.getItem(checklistKey) || "[]"));
  const checklistItems = [
    "I can explain the main definitions in simple words.",
    "I can recall the chapter memory aid without looking.",
    "I can connect at least one attack to one prevention measure.",
    "I reviewed the slide coverage list for this chapter."
  ];
  content.innerHTML = `
    <div class="tool-layout">
      <section class="tool-card">
        <h3>Probability x Impact calculator</h3>
        <p>Uses the Chapter 1 ranking values: High = 15, Medium = 10, Low = 5.</p>
        <label class="form-row">Probability
          <select id="probability">
            <option value="15">High (15)</option>
            <option value="10">Medium (10)</option>
            <option value="5">Low (5)</option>
          </select>
        </label>
        <label class="form-row">Impact
          <select id="impact">
            <option value="15">High (15)</option>
            <option value="10">Medium (10)</option>
            <option value="5">Low (5)</option>
          </select>
        </label>
        <div id="riskResult" class="result-box"></div>
      </section>
      <section class="tool-card">
        <h3>DREAD average</h3>
        <p>Use 0, 5, or 10 for each DREAD factor, then average them.</p>
        ${["Damage", "Reproducibility", "Exploitability", "Affected Users", "Discoverability"].map((label, index) => `
          <label class="form-row">${label}: <span id="dreadValue${index}">5</span>
            <input type="range" class="dread" min="0" max="10" step="5" value="5" data-label="${label}" data-index="${index}">
          </label>
        `).join("")}
        <div id="dreadResult" class="result-box"></div>
      </section>
      <section class="tool-card">
        <h3>Chapter study checklist</h3>
        <p>Saved in this browser for quick revision tracking.</p>
        <div class="checklist">
          ${checklistItems.map((item, index) => `
            <label>
              <input type="checkbox" data-check="${index}" ${saved.has(index) ? "checked" : ""}>
              <span>${escapeHtml(item)}</span>
            </label>
          `).join("")}
        </div>
      </section>
      <section class="tool-card">
        <h3>Source integrity note</h3>
        <p>These notes intentionally avoid outside references. Any memory aid or simplified wording is derived from the provided slides.</p>
        <p>Use the Slide Coverage tab to confirm every slide title from the PDFs is represented.</p>
      </section>
    </div>
  `;

  function updateRisk() {
    const probability = Number(document.querySelector("#probability").value);
    const impact = Number(document.querySelector("#impact").value);
    const score = probability * impact;
    document.querySelector("#riskResult").innerHTML = `<strong>Score: ${score}</strong><span>Approximate level: ${riskLabel(score)}</span>`;
  }

  function updateDread() {
    const values = [...document.querySelectorAll(".dread")].map((input) => Number(input.value));
    values.forEach((value, index) => {
      document.querySelector(`#dreadValue${index}`).textContent = value;
    });
    const average = values.reduce((sum, value) => sum + value, 0) / values.length;
    document.querySelector("#dreadResult").innerHTML = `<strong>Average: ${average.toFixed(1)}</strong><span>Formula: (D + R + E + A + D) / 5</span>`;
  }

  document.querySelectorAll("#probability, #impact").forEach((input) => input.addEventListener("change", updateRisk));
  document.querySelectorAll(".dread").forEach((input) => input.addEventListener("input", updateDread));
  document.querySelectorAll("[data-check]").forEach((checkbox) => {
    checkbox.addEventListener("change", () => {
      const latest = new Set(JSON.parse(localStorage.getItem(checklistKey) || "[]"));
      const index = Number(checkbox.dataset.check);
      if (checkbox.checked) latest.add(index);
      else latest.delete(index);
      localStorage.setItem(checklistKey, JSON.stringify([...latest]));
    });
  });
  updateRisk();
  updateDread();
}

function renderCoverage() {
  const chapterCoverage = COVERAGE[state.chapterIndex];
  if (!chapterCoverage) {
    content.innerHTML = `<div class="empty-state">No coverage data found.</div>`;
    return;
  }
  content.innerHTML = `
    <div class="coverage-card">
      <span class="source">${escapeHtml(chapterCoverage.chapter)}</span>
      <h3>Slide coverage map</h3>
      <p>This list is generated from the PDF slide titles and is included as an audit trail for coverage.</p>
      <div class="coverage-list">
        ${chapterCoverage.slides.map((slide) => `
          <span class="slide-pill"><strong>${String(slide.page).padStart(2, "0")}</strong> ${escapeHtml(slide.title)}</span>
        `).join("")}
      </div>
    </div>
  `;
}

function renderView() {
  tabs.forEach((tab) => tab.classList.toggle("active", tab.dataset.view === state.view));
  if (state.view === "notes") renderNotes();
  if (state.view === "memory") renderMemory();
  if (state.view === "flashcards") renderFlashcards();
  if (state.view === "quiz") renderQuiz();
  if (state.view === "tools") renderTools();
  if (state.view === "coverage") renderCoverage();
}

function render() {
  renderNav();
  renderHeader();
  renderView();
}

tabs.forEach((tab) => {
  tab.addEventListener("click", () => {
    state.view = tab.dataset.view;
    state.flashRevealed = false;
    state.quizAnswered = false;
    renderView();
  });
});

searchInput.addEventListener("input", () => {
  if (state.view !== "notes") {
    state.view = "notes";
  }
  renderView();
});

markCompleteBtn.addEventListener("click", () => {
  const id = currentChapter().id;
  if (state.completed.has(id)) state.completed.delete(id);
  else state.completed.add(id);
  saveCompleted();
  render();
});

render();
